### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by doubletime32** [Wexop/TheThing#1]
I have a suggestion. I DO love the potential of this enemy, but I feel like if the timer of the game is set to 0 or less than 1 second, I feel like he should just jumpscare you without teleporting cause it's not enough time to complete the game anyways depending on the settings. I really enjoy this mod otherwise it's fun

**Comment by Wexop** [comment]
Hello,
I don't think this would be totaly fair, the monster would just kill every players without give any chance to them to survive, the mini game is here for that

**Comment by doubletime32** [comment]
Oh yeah I forgot the whole tracking people thing. I play this game solo a lot so I was used to just avoiding a particular area when I notice him I'm now realizing my feedback sounded more solo orientated. It's definitely a fantastic mod that was my bad XD
