### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by ThinAchiever** [Wexop/TheThing#3]
I love this mod and have not found many issues however, when this mod is used with "Backrooms" mod, both areas overlap, causing it highly unlikely to escape from either. I believe that this could be a simple fix and would love if it was fixed.

**Comment by Wexop** [comment]
Hello !
Thanks for the report, i uploaded v1.0.6 that should fix it

I also added a roomPosY config, so if this issue appear again, just increase it :)

Have fun with The Thing !
